sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - docker pull elasticsearch:latest
  - dps=`docker run -d -p 127.0.0.1:9200:9200 elasticsearch:latest`
  - mvn clean test -DargLine="-DdockerHost=127.0.0.1"
  - docker stop $dps

cache:
  directories:
    - $HOME/.m2
